services:
  redis:
    image: registry.cn-beijing.aliyuncs.com/alphesh-soft/redis:7.0.1
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./users.acl:/etc/redis/users.acl:ro
      - /alphesh/data/redis:/data
    command: >
      redis-server 
      --aclfile /etc/redis/users.acl
      --appendonly yes

volumes:
  redis_data: